name: Deploy container with Z3 but without JAR
run-name: Deploying container
on:
  push:
    branches:
      - base

jobs:
  Build-container:
    runs-on: ubuntu-latest
    env:
      DOCKER_ORG: s4685136
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v2
        with:
            config-inline: |
              [registry."172.26.122.75:5000"]
                http = true
                insecure = true

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: .devcontainer/Dockerfile
          platforms: |
            linux/amd64
          push: true
          tags: |
            172.26.122.75:5000/${{ env.DOCKER_ORG }}/tsn_sched_base:latest

